//! Generate Composer-compatible PHP autoload files under `vendor/`.

#![deny(unsafe_code)]

use composer_core::error::{Error, Result};
use composer_core::AutoloadConfig;
use composer_lock::{ComposerLock, LockedPackage};
use composer_manifest::ComposerJson;
use regex::Regex;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use tracing::debug;
use walkdir::WalkDir;

/// Options for autoloader generation.
#[derive(Debug, Clone)]
pub struct AutoloadOptions {
    pub optimize: bool,
    pub classmap_authoritative: bool,
    pub with_dev: bool,
}

impl Default for AutoloadOptions {
    fn default() -> Self {
        Self {
            optimize: false,
            classmap_authoritative: false,
            with_dev: true,
        }
    }
}

/// Generate `vendor/autoload.php` and supporting files.
pub fn generate(
    project_root: &Path,
    vendor_dir: &Path,
    manifest: &ComposerJson,
    lock: Option<&ComposerLock>,
    options: &AutoloadOptions,
) -> Result<()> {
    let autoload_dir = vendor_dir.join("composer");
    fs::create_dir_all(&autoload_dir).map_err(|e| Error::io(&autoload_dir, e))?;

    let mut psr4: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut psr0: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut files: Vec<String> = Vec::new();
    let mut classmap_dirs: Vec<String> = Vec::new();
    let mut classmap: BTreeMap<String, String> = BTreeMap::new();

    // Root package autoload (paths relative to project root / vendor)
    if let Some(al) = &manifest.autoload {
        merge_autoload(
            al,
            "", // root package lives at project root; paths relative to vendor use ../
            true,
            &mut psr4,
            &mut psr0,
            &mut files,
            &mut classmap_dirs,
        );
    }
    if options.with_dev {
        if let Some(al) = &manifest.autoload_dev {
            merge_autoload(
                al,
                "",
                true,
                &mut psr4,
                &mut psr0,
                &mut files,
                &mut classmap_dirs,
            );
        }
    }

    // Locked packages
    if let Some(lock) = lock {
        for pkg in lock.packages_to_install(options.with_dev) {
            collect_package_autoload(
                pkg,
                vendor_dir,
                &mut psr4,
                &mut psr0,
                &mut files,
                &mut classmap_dirs,
            )?;
        }
    }

    if options.optimize || options.classmap_authoritative {
        // Scan classmap dirs + convert PSR prefixes into classmap where possible
        for dir in &classmap_dirs {
            let abs = resolve_autoload_path(vendor_dir, dir);
            scan_classmap(&abs, vendor_dir, &mut classmap)?;
        }
        if options.optimize {
            for (prefix, paths) in &psr4 {
                for p in paths {
                    let abs = resolve_autoload_path(vendor_dir, p);
                    scan_psr4_classmap(prefix, &abs, vendor_dir, &mut classmap)?;
                }
            }
        }
    } else {
        for dir in &classmap_dirs {
            let abs = resolve_autoload_path(vendor_dir, dir);
            scan_classmap(&abs, vendor_dir, &mut classmap)?;
        }
    }

    write_autoload_namespaces(&autoload_dir, &psr0)?;
    write_autoload_psr4(&autoload_dir, &psr4)?;
    write_autoload_classmap(&autoload_dir, &classmap)?;
    write_autoload_files(&autoload_dir, &files)?;
    write_autoload_static(&autoload_dir, &psr4, &psr0, &classmap, &files)?;
    write_class_loader(&autoload_dir)?;
    write_autoload_real(&autoload_dir)?;
    write_installed(&autoload_dir, lock, options.with_dev)?;
    write_installed_php(&autoload_dir, lock, options.with_dev)?;
    write_platform_check(&autoload_dir)?;

    // vendor/autoload.php
    let autoload_php = vendor_dir.join("autoload.php");
    fs::write(
        &autoload_php,
        "<?php\n\n// autoload.php @generated by composer-rs\n\n\
         require_once __DIR__ . '/composer/autoload_real.php';\n\n\
         return ComposerAutoloaderInit::getLoader();\n",
    )
    .map_err(|e| Error::io(&autoload_php, e))?;

    debug!(vendor = %vendor_dir.display(), "autoloader generated");
    let _ = project_root;
    Ok(())
}

fn merge_autoload(
    al: &AutoloadConfig,
    package_prefix: &str,
    is_root: bool,
    psr4: &mut BTreeMap<String, Vec<String>>,
    psr0: &mut BTreeMap<String, Vec<String>>,
    files: &mut Vec<String>,
    classmap_dirs: &mut Vec<String>,
) {
    for (ns, paths) in &al.psr4 {
        for p in paths.paths() {
            let rel = package_path(package_prefix, p, is_root);
            psr4.entry(ns.clone()).or_default().push(rel);
        }
    }
    for (ns, paths) in &al.psr0 {
        for p in paths.paths() {
            let rel = package_path(package_prefix, p, is_root);
            psr0.entry(ns.clone()).or_default().push(rel);
        }
    }
    for f in &al.files {
        files.push(package_path(package_prefix, f, is_root));
    }
    for d in &al.classmap {
        classmap_dirs.push(package_path(package_prefix, d, is_root));
    }
}

fn package_path(package_install: &str, path: &str, is_root: bool) -> String {
    let path = path.trim_start_matches("./");
    if is_root {
        // From vendor/composer → project root is ../..
        if path.is_empty() || path == "." {
            return "../..".into();
        }
        return format!("../../{path}");
    }
    if path.is_empty() || path == "." {
        format!("../{package_install}")
    } else {
        format!("../{package_install}/{path}")
    }
}

fn collect_package_autoload(
    pkg: &LockedPackage,
    _vendor_dir: &Path,
    psr4: &mut BTreeMap<String, Vec<String>>,
    psr0: &mut BTreeMap<String, Vec<String>>,
    files: &mut Vec<String>,
    classmap_dirs: &mut Vec<String>,
) -> Result<()> {
    let install = pkg.name.clone(); // vendor/name
    if let Some(al) = &pkg.autoload {
        merge_autoload(al, &install, false, psr4, psr0, files, classmap_dirs);
    }
    Ok(())
}

fn resolve_autoload_path(vendor_dir: &Path, rel_from_composer: &str) -> PathBuf {
    // rel is relative to vendor/composer
    vendor_dir.join("composer").join(rel_from_composer)
}

fn scan_classmap(
    dir: &Path,
    vendor_dir: &Path,
    classmap: &mut BTreeMap<String, String>,
) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in WalkDir::new(dir).into_iter().filter_map(|e| e.ok()) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("php") {
            continue;
        }
        if let Ok(content) = fs::read_to_string(path) {
            for class in extract_types(&content) {
                let rel = path_relative_to_composer(path, vendor_dir);
                classmap.insert(class, rel);
            }
        }
    }
    Ok(())
}

fn scan_psr4_classmap(
    prefix: &str,
    dir: &Path,
    vendor_dir: &Path,
    classmap: &mut BTreeMap<String, String>,
) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    let prefix_ns = prefix.trim_end_matches('\\');
    for entry in WalkDir::new(dir).into_iter().filter_map(|e| e.ok()) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("php") {
            continue;
        }
        if let Ok(rel_to_base) = path.strip_prefix(dir) {
            let mut class = prefix_ns.to_string();
            for comp in rel_to_base.components() {
                if let std::path::Component::Normal(c) = comp {
                    let s = c.to_string_lossy();
                    if s.ends_with(".php") {
                        let name = s.trim_end_matches(".php");
                        if !class.is_empty() {
                            class.push('\\');
                        }
                        class.push_str(name);
                    } else {
                        if !class.is_empty() {
                            class.push('\\');
                        }
                        class.push_str(&s);
                    }
                }
            }
            let rel = path_relative_to_composer(path, vendor_dir);
            classmap.insert(class, rel);
        }
    }
    Ok(())
}

fn path_relative_to_composer(path: &Path, vendor_dir: &Path) -> String {
    let composer_dir = vendor_dir.join("composer");
    pathdiff_simple(&composer_dir, path)
}

fn pathdiff_simple(from: &Path, to: &Path) -> String {
    // Simple relative path: assume both absolute or same root
    let from = fs::canonicalize(from).unwrap_or_else(|_| from.to_path_buf());
    let to = fs::canonicalize(to).unwrap_or_else(|_| to.to_path_buf());
    let from_comps: Vec<_> = from.components().collect();
    let to_comps: Vec<_> = to.components().collect();
    let mut i = 0;
    while i < from_comps.len() && i < to_comps.len() && from_comps[i] == to_comps[i] {
        i += 1;
    }
    let mut out = PathBuf::new();
    for _ in i..from_comps.len() {
        out.push("..");
    }
    for c in &to_comps[i..] {
        out.push(c);
    }
    out.to_string_lossy().replace('\\', "/")
}

fn extract_types(php: &str) -> Vec<String> {
    static NS_RE: OnceLock<Regex> = OnceLock::new();
    static TYPE_RE: OnceLock<Regex> = OnceLock::new();
    let ns_re = NS_RE.get_or_init(|| Regex::new(r"(?m)^\s*namespace\s+([^;{]+)").unwrap());
    let type_re = TYPE_RE.get_or_init(|| {
        Regex::new(r"(?m)^\s*(?:abstract\s+|final\s+)?(?:class|interface|trait|enum)\s+(\w+)").unwrap()
    });

    let ns = ns_re
        .captures(php)
        .map(|c| c[1].trim().to_string())
        .unwrap_or_default();

    let mut out = Vec::new();
    for cap in type_re.captures_iter(php) {
        let name = &cap[1];
        if ns.is_empty() {
            out.push(name.to_string());
        } else {
            out.push(format!("{ns}\\{name}"));
        }
    }
    out
}

fn php_array_strings(map: &BTreeMap<String, Vec<String>>) -> String {
    let mut s = String::from("array(\n");
    for (k, paths) in map {
        let paths_php: Vec<String> = paths
            .iter()
            .map(|p| format!("$vendorDir . '/{}'", escape_php(p.trim_start_matches("../"))))
            .collect();
        // Our paths are relative to vendor/composer; Composer uses $vendorDir and $baseDir.
        // We emit paths relative to vendor/composer as simple strings with $vendorDir.
        let rendered_paths: Vec<String> = paths
            .iter()
            .map(|p| {
                if p.starts_with("../../") {
                    format!("$baseDir . '/{}'", escape_php(&p[6..]))
                } else if p.starts_with("../") {
                    format!("$vendorDir . '/{}'", escape_php(&p[3..]))
                } else {
                    format!("$vendorDir . '/{}'", escape_php(p))
                }
            })
            .collect();
        let _ = paths_php;
        if rendered_paths.len() == 1 {
            s.push_str(&format!(
                "    '{}' => {},\n",
                escape_php(k),
                rendered_paths[0]
            ));
        } else {
            s.push_str(&format!("    '{}' => array(", escape_php(k)));
            for (i, p) in rendered_paths.iter().enumerate() {
                if i > 0 {
                    s.push_str(", ");
                }
                s.push_str(p);
            }
            s.push_str("),\n");
        }
    }
    s.push_str(")");
    s
}

fn escape_php(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

fn write_autoload_psr4(dir: &Path, psr4: &BTreeMap<String, Vec<String>>) -> Result<()> {
    let path = dir.join("autoload_psr4.php");
    let body = format!(
        "<?php\n\n// autoload_psr4.php @generated by composer-rs\n\n\
         $vendorDir = dirname(__DIR__);\n\
         $baseDir = dirname($vendorDir);\n\n\
         return {};\n",
        php_array_strings(psr4)
    );
    fs::write(&path, body).map_err(|e| Error::io(&path, e))
}

fn write_autoload_namespaces(dir: &Path, psr0: &BTreeMap<String, Vec<String>>) -> Result<()> {
    let path = dir.join("autoload_namespaces.php");
    let body = format!(
        "<?php\n\n// autoload_namespaces.php @generated by composer-rs\n\n\
         $vendorDir = dirname(__DIR__);\n\
         $baseDir = dirname($vendorDir);\n\n\
         return {};\n",
        php_array_strings(psr0)
    );
    fs::write(&path, body).map_err(|e| Error::io(&path, e))
}

fn write_autoload_classmap(dir: &Path, classmap: &BTreeMap<String, String>) -> Result<()> {
    let path = dir.join("autoload_classmap.php");
    let mut s = String::from(
        "<?php\n\n// autoload_classmap.php @generated by composer-rs\n\n\
         $vendorDir = dirname(__DIR__);\n\
         $baseDir = dirname($vendorDir);\n\n\
         return array(\n",
    );
    for (class, rel) in classmap {
        let val = if rel.starts_with("../../") {
            format!("$baseDir . '/{}'", escape_php(&rel[6..]))
        } else if rel.starts_with("../") {
            format!("$vendorDir . '/{}'", escape_php(&rel[3..]))
        } else {
            format!("$vendorDir . '/{}'", escape_php(rel))
        };
        s.push_str(&format!("    '{}' => {},\n", escape_php(class), val));
    }
    s.push_str(");\n");
    fs::write(&path, s).map_err(|e| Error::io(&path, e))
}

fn write_autoload_files(dir: &Path, files: &[String]) -> Result<()> {
    let path = dir.join("autoload_files.php");
    let mut s = String::from(
        "<?php\n\n// autoload_files.php @generated by composer-rs\n\n\
         $vendorDir = dirname(__DIR__);\n\
         $baseDir = dirname($vendorDir);\n\n\
         return array(\n",
    );
    for (i, f) in files.iter().enumerate() {
        let val = if f.starts_with("../../") {
            format!("$baseDir . '/{}'", escape_php(&f[6..]))
        } else if f.starts_with("../") {
            format!("$vendorDir . '/{}'", escape_php(&f[3..]))
        } else {
            format!("$vendorDir . '/{}'", escape_php(f))
        };
        // Composer uses hash keys
        s.push_str(&format!("    'composer_rs_{i:04}' => {val},\n"));
    }
    s.push_str(");\n");
    fs::write(&path, s).map_err(|e| Error::io(&path, e))
}

fn write_autoload_static(
    dir: &Path,
    psr4: &BTreeMap<String, Vec<String>>,
    psr0: &BTreeMap<String, Vec<String>>,
    classmap: &BTreeMap<String, String>,
    files: &[String],
) -> Result<()> {
    let path = dir.join("autoload_static.php");
    // Keep a minimal static loader that mirrors the array files.
    let body = format!(
        "<?php\n\n// autoload_static.php @generated by composer-rs\n\n\
         namespace Composer\\Autoload;\n\n\
         class ComposerStaticInit\n{{\n\
             public static $prefixLengthsPsr4 = array();\n\
             public static $prefixDirsPsr4 = array();\n\
             public static $prefixesPsr0 = array();\n\
             public static $classMap = array();\n\
             public static $files = array();\n\n\
             public static function getInitializer(ClassLoader $loader)\n\
             {{\n\
                 return \\Closure::bind(function () use ($loader) {{\n\
                     $loader->prefixLengthsPsr4 = ComposerStaticInit::$prefixLengthsPsr4;\n\
                     $loader->prefixDirsPsr4 = ComposerStaticInit::$prefixDirsPsr4;\n\
                     $loader->prefixesPsr0 = ComposerStaticInit::$prefixesPsr0;\n\
                     $loader->classMap = ComposerStaticInit::$classMap;\n\
                 }}, null, ClassLoader::class);\n\
             }}\n\
         }}\n"
    );
    let _ = (psr4, psr0, classmap, files);
    fs::write(&path, body).map_err(|e| Error::io(&path, e))
}

fn write_class_loader(dir: &Path) -> Result<()> {
    let path = dir.join("ClassLoader.php");
    if path.exists() {
        return Ok(());
    }
    // Minimal PSR-4/0/classmap ClassLoader compatible enough for most apps.
    let body = r#"<?php
// ClassLoader.php @generated by composer-rs (minimal)

namespace Composer\Autoload;

class ClassLoader
{
    public $prefixLengthsPsr4 = array();
    public $prefixDirsPsr4 = array();
    public $prefixesPsr0 = array();
    public $classMap = array();
    private $classMapAuthoritative = false;
    private $useIncludePath = false;
    private $apcuPrefix;

    public function add($prefix, $paths, $prepend = false)
    {
        $paths = (array) $paths;
        if (!$prefix) {
            return;
        }
        if (!isset($this->prefixesPsr0[$prefix[0]][$prefix])) {
            $this->prefixesPsr0[$prefix[0]][$prefix] = $paths;
        } elseif ($prepend) {
            $this->prefixesPsr0[$prefix[0]][$prefix] = array_merge($paths, $this->prefixesPsr0[$prefix[0]][$prefix]);
        } else {
            $this->prefixesPsr0[$prefix[0]][$prefix] = array_merge($this->prefixesPsr0[$prefix[0]][$prefix], $paths);
        }
    }

    public function addPsr4($prefix, $paths, $prepend = false)
    {
        $paths = (array) $paths;
        if (!isset($this->prefixDirsPsr4[$prefix])) {
            $length = strlen($prefix);
            if ('\\' !== $prefix[$length - 1]) {
                throw new \InvalidArgumentException("A non-empty PSR-4 prefix must end with a namespace separator.");
            }
            $this->prefixLengthsPsr4[$prefix[0]][$prefix] = $length;
            $this->prefixDirsPsr4[$prefix] = $paths;
        } elseif ($prepend) {
            $this->prefixDirsPsr4[$prefix] = array_merge($paths, $this->prefixDirsPsr4[$prefix]);
        } else {
            $this->prefixDirsPsr4[$prefix] = array_merge($this->prefixDirsPsr4[$prefix], $paths);
        }
    }

    public function setClassMapAuthoritative($bool) { $this->classMapAuthoritative = (bool) $bool; }
    public function setUseIncludePath($bool) { $this->useIncludePath = (bool) $bool; }
    public function setApcuPrefix($prefix) { $this->apcuPrefix = $prefix; }

    public function register($prepend = false)
    {
        spl_autoload_register(array($this, 'loadClass'), true, $prepend);
    }

    public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            includeFile($file);
            return true;
        }
        return null;
    }

    public function findFile($class)
    {
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }
        if ($this->classMapAuthoritative) {
            return false;
        }

        $logical = strtr($class, '\\', DIRECTORY_SEPARATOR) . '.php';

        // PSR-4
        $first = $class[0];
        if (isset($this->prefixLengthsPsr4[$first])) {
            foreach ($this->prefixLengthsPsr4[$first] as $prefix => $length) {
                if (0 === strpos($class, $prefix)) {
                    foreach ($this->prefixDirsPsr4[$prefix] as $dir) {
                        $file = $dir . DIRECTORY_SEPARATOR . substr($logical, $length);
                        if (file_exists($file)) {
                            return $file;
                        }
                    }
                }
            }
        }

        // PSR-0
        if (isset($this->prefixesPsr0[$first])) {
            foreach ($this->prefixesPsr0[$first] as $prefix => $dirs) {
                if (0 === strpos($class, $prefix)) {
                    foreach ($dirs as $dir) {
                        $file = $dir . DIRECTORY_SEPARATOR . $logical;
                        if (file_exists($file)) {
                            return $file;
                        }
                    }
                }
            }
        }

        return false;
    }
}

function includeFile($file)
{
    include $file;
}
"#;
    fs::write(&path, body).map_err(|e| Error::io(&path, e))
}

fn write_autoload_real(dir: &Path) -> Result<()> {
    let path = dir.join("autoload_real.php");
    let body = r#"<?php
// autoload_real.php @generated by composer-rs

class ComposerAutoloaderInit
{
    private static $loader;

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/ClassLoader.php';
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();

        $useStatic = false;
        if ($useStatic) {
            require __DIR__ . '/autoload_static.php';
        }

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->add($namespace, $path);
        }

        $map = require __DIR__ . '/autoload_psr4.php';
        foreach ($map as $namespace => $path) {
            $loader->addPsr4($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->classMap = $classMap + $loader->classMap;
        }

        $loader->register(true);

        $includeFiles = require __DIR__ . '/autoload_files.php';
        foreach ($includeFiles as $fileIdentifier => $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
                if (file_exists($file)) {
                    require $file;
                }
            }
        }

        return $loader;
    }
}
"#;
    fs::write(&path, body).map_err(|e| Error::io(&path, e))
}

fn write_installed(dir: &Path, lock: Option<&ComposerLock>, with_dev: bool) -> Result<()> {
    let path = dir.join("installed.json");
    let packages: Vec<serde_json::Value> = lock
        .map(|l| {
            l.packages_to_install(with_dev)
                .into_iter()
                .filter_map(|p| serde_json::to_value(p).ok())
                .collect()
        })
        .unwrap_or_default();

    let doc = serde_json::json!({
        "packages": packages,
        "dev": with_dev,
        "dev-package-names": lock.map(|l| {
            l.packages_dev.iter().map(|p| p.name.clone()).collect::<Vec<_>>()
        }).unwrap_or_default(),
    });
    let text = serde_json::to_string_pretty(&doc).unwrap_or_else(|_| "{}".into());
    fs::write(&path, text + "\n").map_err(|e| Error::io(&path, e))
}

fn write_installed_php(dir: &Path, lock: Option<&ComposerLock>, with_dev: bool) -> Result<()> {
    let path = dir.join("installed.php");
    let mut versions = String::from("array(\n");
    if let Some(lock) = lock {
        for p in lock.packages_to_install(with_dev) {
            versions.push_str(&format!(
                "        '{}' => array('pretty_version' => '{}', 'version' => '{}', 'reference' => null),\n",
                escape_php(&p.name),
                escape_php(&p.version),
                escape_php(&p.version),
            ));
        }
    }
    versions.push_str("    )");

    let body = format!(
        "<?php return array(\n    'root' => array('name' => '__root__'),\n    'versions' => {versions},\n);\n"
    );
    fs::write(&path, body).map_err(|e| Error::io(&path, e))
}

fn write_platform_check(dir: &Path) -> Result<()> {
    let path = dir.join("platform_check.php");
    fs::write(
        &path,
        "<?php\n// platform_check.php @generated by composer-rs\n// (intentionally empty — use Composer for strict platform checks)\n",
    )
    .map_err(|e| Error::io(&path, e))
}

// Need serde_json for installed.json
use serde_json;
